using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text;

namespace UnitTests.Characterization
{
    internal static class PublicApiSnapshot
    {
        private const BindingFlags DeclaredPublic =
            BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;

        // These types belong to pending, uncommitted work in the current workspace.
        // Do not let that work leak into the reviewed PR 1 API contract.
        private static readonly HashSet<string> ExcludedTypeNames = new(StringComparer.Ordinal)
        {
            "NurbsSharp.Core.ContinuityResult",
            "NurbsSharp.Core.ContinuityType",
        };

        internal static string Generate(Assembly assembly)
        {
            var lines = new List<string>
            {
                "# NurbsSharp public API",
                "# Generated by PublicApiSnapshot; ordinal sort; LF line endings.",
            };

            foreach (Type type in assembly.GetExportedTypes()
                         .Where(type => type.Namespace?.StartsWith("NurbsSharp", StringComparison.Ordinal) == true)
                         .Where(type => !ContainsExcludedType(type))
                         .OrderBy(type => type.FullName, StringComparer.Ordinal))
            {
                lines.Add(string.Empty);
                lines.Add(FormatTypeDeclaration(type));

                IEnumerable<string> members = type.GetConstructors(DeclaredPublic)
                    .Where(constructor => !constructor.GetParameters().Any(parameter => ContainsExcludedType(parameter.ParameterType)))
                    .Select(FormatConstructor)
                    .Concat(type.GetProperties(DeclaredPublic)
                        .Where(property => !ContainsExcludedType(property.PropertyType))
                        .Where(property => !property.GetIndexParameters().Any(parameter => ContainsExcludedType(parameter.ParameterType)))
                        .Select(FormatProperty))
                    .Concat(type.GetFields(DeclaredPublic)
                        .Where(field => !ContainsExcludedType(field.FieldType))
                        .Select(FormatField))
                    .Concat(type.GetEvents(DeclaredPublic)
                        .Where(eventInfo => eventInfo.EventHandlerType is null || !ContainsExcludedType(eventInfo.EventHandlerType))
                        .Select(FormatEvent))
                    .Concat(type.GetMethods(DeclaredPublic)
                        .Where(method => !method.IsSpecialName || method.Name.StartsWith("op_", StringComparison.Ordinal))
                        .Where(method => !ContainsExcludedType(method.ReturnType))
                        .Where(method => !method.GetParameters().Any(parameter => ContainsExcludedType(parameter.ParameterType)))
                        .Select(FormatMethod))
                    .OrderBy(member => member, StringComparer.Ordinal);

                lines.AddRange(members.Select(member => "  " + member));
            }

            return string.Join("\n", lines) + "\n";
        }

        private static bool ContainsExcludedType(Type type)
        {
            if (type.IsByRef || type.IsArray || type.IsPointer)
                return ContainsExcludedType(type.GetElementType()!);
            if (type.IsGenericType && type.GetGenericArguments().Any(ContainsExcludedType))
                return true;

            return type.FullName is not null && ExcludedTypeNames.Contains(type.FullName);
        }

        private static string FormatTypeDeclaration(Type type)
        {
            string kind = type.IsEnum ? "enum"
                : type.IsValueType ? "struct"
                : type.IsInterface ? "interface"
                : type.IsAbstract && type.IsSealed ? "static class"
                : "class";
            string baseType = type.BaseType is null || type.BaseType == typeof(object) || type.IsEnum || type.IsValueType
                ? string.Empty
                : " : " + FormatType(type.BaseType);
            return $"{kind} {FormatType(type)}{baseType}";
        }

        private static string FormatConstructor(ConstructorInfo constructor)
        {
            return $"ctor {FormatType(constructor.DeclaringType!)}({FormatParameters(constructor.GetParameters())})";
        }

        private static string FormatProperty(PropertyInfo property)
        {
            MethodInfo? accessor = property.GetMethod ?? property.SetMethod;
            string staticPrefix = accessor?.IsStatic == true ? "static " : string.Empty;
            string indexParameters = property.GetIndexParameters().Length == 0
                ? string.Empty
                : $"[{FormatParameters(property.GetIndexParameters())}]";
            string accessors = $"{{{(property.GetMethod is null ? string.Empty : " get;")}{(property.SetMethod is null ? string.Empty : " set;")} }}";
            return $"property {staticPrefix}{FormatType(property.PropertyType)} {property.Name}{indexParameters} {accessors}";
        }

        private static string FormatField(FieldInfo field)
        {
            string modifier = field.IsLiteral ? "const " : field.IsStatic ? "static " : string.Empty;
            string value = field.IsLiteral ? " = " + FormatDefault(field.GetRawConstantValue(), field.FieldType) : string.Empty;
            return $"field {modifier}{FormatType(field.FieldType)} {field.Name}{value}";
        }

        private static string FormatEvent(EventInfo eventInfo)
        {
            MethodInfo? accessor = eventInfo.AddMethod ?? eventInfo.RemoveMethod;
            string staticPrefix = accessor?.IsStatic == true ? "static " : string.Empty;
            return $"event {staticPrefix}{FormatType(eventInfo.EventHandlerType!)} {eventInfo.Name}";
        }

        private static string FormatMethod(MethodInfo method)
        {
            string staticPrefix = method.IsStatic ? "static " : string.Empty;
            string genericParameters = method.IsGenericMethodDefinition
                ? "<" + string.Join(",", method.GetGenericArguments().Select(argument => argument.Name)) + ">"
                : string.Empty;
            return $"method {staticPrefix}{FormatType(method.ReturnType)} {method.Name}{genericParameters}({FormatParameters(method.GetParameters())})";
        }

        private static string FormatParameters(IReadOnlyList<ParameterInfo> parameters)
        {
            return string.Join(", ", parameters.Select(FormatParameter));
        }

        private static string FormatParameter(ParameterInfo parameter)
        {
            Type parameterType = parameter.ParameterType;
            string direction = string.Empty;
            if (parameterType.IsByRef)
            {
                direction = parameter.IsOut ? "out " : parameter.IsIn ? "in " : "ref ";
                parameterType = parameterType.GetElementType()!;
            }

            string optional = parameter.HasDefaultValue
                ? " = " + FormatDefault(parameter.DefaultValue, parameterType)
                : string.Empty;
            return $"{direction}{FormatType(parameterType)} {parameter.Name}{optional}";
        }

        private static string FormatDefault(object? value, Type declaredType)
        {
            if (value is null)
                return "null";
            if (value == DBNull.Value || value == Missing.Value)
                return "missing";
            if (declaredType.IsEnum)
                return FormatType(declaredType) + "." + Enum.GetName(declaredType, value);

            return value switch
            {
                string text => "\"" + text.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"",
                char character => "'" + character + "'",
                bool boolean => boolean ? "true" : "false",
                double number => number.ToString("R", CultureInfo.InvariantCulture),
                float number => number.ToString("R", CultureInfo.InvariantCulture),
                IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture),
                _ => value.ToString() ?? string.Empty,
            };
        }

        private static string FormatType(Type type)
        {
            if (type.IsByRef)
                return FormatType(type.GetElementType()!);
            if (type.IsArray)
                return FormatType(type.GetElementType()!) + "[" + new string(',', type.GetArrayRank() - 1) + "]";
            if (type.IsGenericParameter)
                return type.Name;
            if (type.IsGenericType)
            {
                string definitionName = type.GetGenericTypeDefinition().FullName ?? type.Name;
                definitionName = definitionName[..definitionName.IndexOf('`')].Replace('+', '.');
                return definitionName + "<" + string.Join(",", type.GetGenericArguments().Select(FormatType)) + ">";
            }

            return (type.FullName ?? type.Name).Replace('+', '.');
        }
    }
}
